### ISSUE TITLE
Can I reuse this code? Please add a license

### ISSUE THREAD

**Issue by intgr** [pftbest/x11-rust-example#1]
Hi! Thanks for creating this, I used some example code from this repository in my project to get started with the X11 API (https://github.com/intgr/ego/pull/89)

The repository name seems to imply that it's fine to incorporate snippets into other projects. But to be sure, I would suggest adding an explicit permissive license like the MIT License (compatible with most licenses) or [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) (the most permissive).

You can use the GitHub license helper https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by pftbest** [comment]
Thanks for reminder.
